bodies:
  files:
  - ./bodies/0.xml
  - ./bodies/1.xml
  - ./bodies/2.xml
  - ./bodies/3.xml
  - ./bodies/4.xml
  - ./bodies/5.xml
  - ./bodies/6.xml
  - ./bodies/7.xml
  - ./bodies/8.xml
  - ./bodies/9.xml
  - ./bodies/10.xml
  - ./bodies/11.xml
  - ./bodies/12.xml
  - ./bodies/13.xml
  - ./bodies/14.xml
  - ./bodies/15.xml
  - ./bodies/16.xml
  - ./bodies/17.xml
  - ./bodies/18.xml
  - ./bodies/19.xml
  - ./bodies/20.xml
  - ./bodies/21.xml
  - ./bodies/22.xml
  - ./bodies/23.xml
  - ./bodies/24.xml
  - ./bodies/25.xml
  - ./bodies/26.xml
  - ./bodies/27.xml
  - ./bodies/28.xml
  - ./bodies/29.xml
  - ./bodies/30.xml
  - ./bodies/31.xml
  - ./bodies/32.xml
  - ./bodies/33.xml
  - ./bodies/34.xml
  - ./bodies/35.xml
  - ./bodies/36.xml
  - ./bodies/37.xml
  - ./bodies/38.xml
  - ./bodies/39.xml
  - ./bodies/40.xml
  - ./bodies/41.xml
  - ./bodies/42.xml
  - ./bodies/43.xml
  - ./bodies/44.xml
  - ./bodies/45.xml
  - ./bodies/46.xml
  - ./bodies/47.xml
  - ./bodies/48.xml
  - ./bodies/49.xml
  - ./bodies/50.xml
  - ./bodies/51.xml
  - ./bodies/52.xml
  - ./bodies/53.xml
  - ./bodies/54.xml
  - ./bodies/55.xml
  - ./bodies/56.xml
  - ./bodies/57.xml
  - ./bodies/58.xml
  - ./bodies/59.xml
  - ./bodies/60.xml
  - ./bodies/61.xml
  - ./bodies/62.xml
  - ./bodies/63.xml
  - ./bodies/64.xml
  - ./bodies/65.xml
  - ./bodies/66.xml
  - ./bodies/67.xml
  - ./bodies/68.xml
  - ./bodies/69.xml
  - ./bodies/70.xml
  - ./bodies/71.xml
  - ./bodies/72.xml
  - ./bodies/73.xml
  - ./bodies/74.xml
  - ./bodies/75.xml
  - ./bodies/76.xml
  - ./bodies/77.xml
  - ./bodies/78.xml
  - ./bodies/79.xml
  - ./bodies/80.xml
  - ./bodies/81.xml
  - ./bodies/82.xml
  - ./bodies/83.xml
  - ./bodies/84.xml
  - ./bodies/85.xml
  - ./bodies/86.xml
  - ./bodies/87.xml
  - ./bodies/88.xml
  - ./bodies/89.xml
  - ./bodies/90.xml
  - ./bodies/91.xml
  - ./bodies/92.xml
  - ./bodies/93.xml
  - ./bodies/94.xml
  - ./bodies/95.xml
  - ./bodies/96.xml
  - ./bodies/97.xml
  - ./bodies/98.xml
  - ./bodies/99.xml
  params:
  - ./params/0.yaml
  - ./params/1.yaml
  - ./params/2.yaml
  - ./params/3.yaml
  - ./params/4.yaml
  - ./params/5.yaml
  - ./params/6.yaml
  - ./params/7.yaml
  - ./params/8.yaml
  - ./params/9.yaml
  - ./params/10.yaml
  - ./params/11.yaml
  - ./params/12.yaml
  - ./params/13.yaml
  - ./params/14.yaml
  - ./params/15.yaml
  - ./params/16.yaml
  - ./params/17.yaml
  - ./params/18.yaml
  - ./params/19.yaml
  - ./params/20.yaml
  - ./params/21.yaml
  - ./params/22.yaml
  - ./params/23.yaml
  - ./params/24.yaml
  - ./params/25.yaml
  - ./params/26.yaml
  - ./params/27.yaml
  - ./params/28.yaml
  - ./params/29.yaml
  - ./params/30.yaml
  - ./params/31.yaml
  - ./params/32.yaml
  - ./params/33.yaml
  - ./params/34.yaml
  - ./params/35.yaml
  - ./params/36.yaml
  - ./params/37.yaml
  - ./params/38.yaml
  - ./params/39.yaml
  - ./params/40.yaml
  - ./params/41.yaml
  - ./params/42.yaml
  - ./params/43.yaml
  - ./params/44.yaml
  - ./params/45.yaml
  - ./params/46.yaml
  - ./params/47.yaml
  - ./params/48.yaml
  - ./params/49.yaml
  - ./params/50.yaml
  - ./params/51.yaml
  - ./params/52.yaml
  - ./params/53.yaml
  - ./params/54.yaml
  - ./params/55.yaml
  - ./params/56.yaml
  - ./params/57.yaml
  - ./params/58.yaml
  - ./params/59.yaml
  - ./params/60.yaml
  - ./params/61.yaml
  - ./params/62.yaml
  - ./params/63.yaml
  - ./params/64.yaml
  - ./params/65.yaml
  - ./params/66.yaml
  - ./params/67.yaml
  - ./params/68.yaml
  - ./params/69.yaml
  - ./params/70.yaml
  - ./params/71.yaml
  - ./params/72.yaml
  - ./params/73.yaml
  - ./params/74.yaml
  - ./params/75.yaml
  - ./params/76.yaml
  - ./params/77.yaml
  - ./params/78.yaml
  - ./params/79.yaml
  - ./params/80.yaml
  - ./params/81.yaml
  - ./params/82.yaml
  - ./params/83.yaml
  - ./params/84.yaml
  - ./params/85.yaml
  - ./params/86.yaml
  - ./params/87.yaml
  - ./params/88.yaml
  - ./params/89.yaml
  - ./params/90.yaml
  - ./params/91.yaml
  - ./params/92.yaml
  - ./params/93.yaml
  - ./params/94.yaml
  - ./params/95.yaml
  - ./params/96.yaml
  - ./params/97.yaml
  - ./params/98.yaml
  - ./params/99.yaml
  total: 100
dataset_name: walker2d
gym_env:
  class: Walker2DEnv
  env_id: Walker2Ds-v0
  filename: env/walker2d.py
